# Focus on version 1.0 as our assumption of this article's dataset
- https://www.tycho.pitt.edu/data/level3.php?utm_source=chatgpt.com, LEVEL 1 Data, version 1.0.0
- Article: https://academic.oup.com/ofid/article/5/7/ofy137/5039595

In [1]:
import pandas as pd

df = pd.read_csv('tycho/ProjectTycho_Level1_v1.0.0.csv', low_memory=False)
df.head()

   epi_week state        loc loc_type      disease cases  incidence_per_100000
0    196601    MN  MINNESOTA    STATE  HEPATITIS A     3                  0.08
1    196601    CO   COLORADO    STATE  HEPATITIS A     1                  0.05
2    196601    AZ    ARIZONA    STATE  HEPATITIS A     6                  0.37
3    196601    MT    MONTANA    STATE  HEPATITIS A     2                  0.28
4    196601    LA  LOUISIANA    STATE  HEPATITIS A     1                  0.03

In [2]:
df['year'] = (
    df['epi_week']
    .astype(str)
    .str[:4]
    .astype(int)
)

df['cases'] = pd.to_numeric(
    df['cases'],
    errors='coerce'
)

In [3]:
df.head()

,epi_week,state,loc,loc_type,disease,cases,incidence_per_100000,year
0,196601,MN,MINNESOTA,STATE,HEPATITIS A,3.0,0.08,1966
1,196601,CO,COLORADO,STATE,HEPATITIS A,1.0,0.05,1966
2,196601,AZ,ARIZONA,STATE,HEPATITIS A,6.0,0.37,1966
3,196601,MT,MONTANA,STATE,HEPATITIS A,2.0,0.28,1966
4,196601,LA,LOUISIANA,STATE,HEPATITIS A,1.0,0.03,1966

In [4]:
exclude_regions = [
    'HI',
    'AK',
]

measles_df = df[(df["disease"] == "MEASLES" )
                & (df['loc_type'] == "STATE")
                & (~df['state'].isin(exclude_regions))
                & (df['year'] >= 1931) 
                & (df['year'] <= 1992) 
                ].drop_duplicates()

measles_df.head()

,epi_week,state,loc,loc_type,disease,cases,incidence_per_100000,year
97355,193101,NY,NEW YORK,STATE,MEASLES,376.0,2.93,1931
97356,193101,OR,OREGON,STATE,MEASLES,67.0,6.94,1931
97357,193101,CO,COLORADO,STATE,MEASLES,41.0,3.88,1931
97358,193101,AZ,ARIZONA,STATE,MEASLES,50.0,11.66,1931
97359,193101,MO,MISSOURI,STATE,MEASLES,1160.0,31.26,1931

In [5]:
print("Regions:", measles_df['state'].nunique())
print("Rows:", len(measles_df))
print("First week:", measles_df['epi_week'].min())
print("Last week:", measles_df['epi_week'].max())
print("Total cases:", measles_df['cases'].sum())

Regions: 49
Rows: 128308
First week: 193101
Last week: 199252
Total cases: 17399916.0

# Let's start imputing - filling missing weeks

In [ ]:
for state in measles_df['state'].unique():
    
    state_df = measles_df

NY
OR
CO
AZ
MO
WI
DC
IN
MA
IA
KY
AL
MI
CA
LA
OH
MN
KS
OK
NE
WA
SD
NJ
FL
TX
GA
ID
AR
TN
PA
WV
DE
MT
IL
NH
RI
VT
CT
ME
NC
SC
MD
NM
WY
UT
ND
VA
MS
NV