# This notebook is to provide code for the streamlit page - app/pages/control.py

In [1]:
import pandas as pd

df = pd.read_csv('app/data/tycho_measles_control.csv')
df.head()

   week state   cases  year
0     1    NY   376.0  1931
1     1    OR    67.0  1931
2     1    CO    41.0  1931
3     1    AZ    50.0  1931
4     1    MO  1160.0  1931

### Let's create a simple line graph to compare the article's results and ours

- we calculated 17% missing weekly data rather than the article's claim on 32%. It's possible this dataset was updated after their publication
- our focus is on the results for our observed cases

| Period         |     Years | Your results |      Paper | Difference | % Difference |
| -------------- | --------: | -----------: | ---------: | ---------: | -----------: |
| Prevaccination | 1931–1963 |   16,744,994 | 16,810,000 |    −65,006 |   **−0.39%** |
| Introduction   | 1964–1970 |  1,121,203.5 |  1,140,000 |  −18,796.5 |   **−1.65%** |
| 1-dose vaccine | 1971–1989 |      394,828 |    390,000 |     +4,828 |   **+1.24%** |

In [5]:
def compare_control_measles_dates(df):
    columns = [
    "Period",
    "Years",
    "Our Results",
    "Paper",
    "Difference",
    "% Difference"
    ]

    full_df = pd.DataFrame(columns=columns)

    prevaccination = df[(df['year'] >= 1931) & (df['year'] <= 1963)]
    prevaccination_cases = round(prevaccination['cases'].sum(), 2)

    introduction = df[(df['year'] >= 1964) & (df['year'] <= 1970)]
    introduction_cases = round(introduction['cases'].sum(), 2)

    one_dose_vaccine = df[(df['year'] >= 1971) & (df['year'] <= 1989)]
    one_dose_vaccine_cases = round(one_dose_vaccine['cases'].sum(), 2)

    prevaccination_control_cases = 16810000
    introduction_control_cases = 1140000
    one_dose_vaccine_control_case = 390000

    prevaccination_diff = abs(prevaccination_cases - prevaccination_control_cases)
    introduction_diff = abs(introduction_cases - introduction_control_cases)
    one_dose_vaccine_diff = abs(one_dose_vaccine_cases - one_dose_vaccine_control_case)

    prevaccination_diff_per = round(prevaccination_diff / prevaccination_control_cases * 100, 2)
    introduction_diff_per = round(introduction_diff / introduction_control_cases * 100, 2)
    one_dose_vaccine_diff_per = round(one_dose_vaccine_diff / one_dose_vaccine_control_case * 100, 2)

    full_df.loc[len(full_df)] = pd.Series(
        ["Prevaccination", "1931–1963", prevaccination_cases, prevaccination_control_cases, 
            prevaccination_diff, prevaccination_diff_per],
        index=columns
    )

    full_df.loc[len(full_df)] = pd.Series(
        ["Introduction", "1964–1970", introduction_cases, introduction_control_cases, 
            introduction_diff, introduction_diff_per],
        index=columns
    )

    full_df.loc[len(full_df)] = pd.Series(
        ["1-dose vaccine", "1971–1989", one_dose_vaccine_cases, one_dose_vaccine_control_case, 
            one_dose_vaccine_diff, one_dose_vaccine_diff_per],
        index=columns
    )

    return full_df

In [7]:
compared_df = compare_control_measles_dates(df)
compared_df

           Period      Years Our Results     Paper Difference % Difference
0  Prevaccination  1931–1963  16744994.0  16810000    65006.0         0.39
1    Introduction  1964–1970   1121203.5   1140000    18796.5         1.65
2  1-dose vaccine  1971–1989    394828.0    390000     4828.0         1.24

In [ ]:
import plotly.graph_objects as go


def table_control_measles_compare(df):
    fig = go.Figure(
        data=[
            go.Table(
                header=dict(
                    values=list(df.columns),
                    align="left"
                ),
                cells=dict(
                    values=[df[col] for col in df.columns],
                    align="left"
                )
            )
        ]
    )

    fig.show()

In [9]:
import plotly.express as px

def graph_comparisons_measles_control(df):

    fig = px.line(
        df,
        x="Period",
        y=["Our Results", "Paper"],
        markers=True,
        title="Comparison of Our Results with the Paper"
    )

    fig.update_layout(
        xaxis_title="Vaccination Period",
        yaxis_title="Measles Cases",
        legend_title="Source"
    )

    fig.show()

In [10]:
graph_comparisons_measles_control(compared_df)